name = "game-hub"
compatibility_date = "2024-03-19"
pages_build_output_dir = ".output"

[env.production]
DATABASE_URL = "file:./d1.db"
NODE_ENV = "production"

[[env.production.d1_databases]]
binding = "DB"
database_name = "game-hub-db"
database_id = "4f423a8e-1a30-42d5-ae6a-1d051d3b22e9" 