name = "game-hub"
compatibility_date = "2024-03-19"

[env.production]
DATABASE_URL = "file:./d1.db"
NODE_ENV = "production"

[site]
bucket = "out"
entry-point = "."

[build]
command = "npm run build"
publish = "out"

[build.upload]
format = "service-worker"
exclude = [
  "**/*.map",
  "**/*.pack",
  "**/cache/**",
  "**/server/**",
  "**/static/chunks/pages/**",
  "**/static/chunks/webpack/**",
  "**/static/chunks/main/**",
  "**/static/chunks/polyfills/**",
  "**/static/chunks/framework/**",
  "**/static/chunks/commons/**"
]

[[d1_databases]]
binding = "DB"
database_name = "game-hub"
database_id = "your-database-id"

[build.environment]
DATABASE_URL = "file:./d1.db"
NEXTAUTH_URL = "https://game-hub.pages.dev"
NEXTAUTH_SECRET = "your-nextauth-secret"
NODE_VERSION = "18.18.0"
NEXT_PUBLIC_API_URL = "https://api.yourdomain.com" 