name = "game-hub"
compatibility_date = "2024-03-19"
pages_build_output_dir = ".output"

[env.production]
DATABASE_URL = "file:./d1.db"
NODE_ENV = "production"
d1_databases = [
  { binding = "DB", database_name = "game-hub-db", database_id = "4e1c3a0f-b314-4b27-8b8e-d1a08e6f63c2" }
]

[build]
command = "npm install && npx prisma generate && NEXT_TELEMETRY_DISABLED=1 NODE_ENV=production npm run build"
pages_build_output_dir = ".output"

[site]
bucket = ".output"

[build.upload]
format = "service-worker"
exclude = [
  "**/*.map",
  "**/*.pack",
  "**/cache/**",
  "**/server/**",
  "**/static/chunks/pages/**",
  "**/static/chunks/webpack/**",
  "**/static/chunks/main/**",
  "**/static/chunks/polyfills/**",
  "**/static/chunks/framework/**",
  "**/static/chunks/commons/**"
] 