name = "game-hub"
compatibility_date = "2024-03-19"
pages_build_output_dir = ".next"

[[d1_databases]]
binding = "DB"
database_name = "game-hub-db"
database_id = "your-database-id"
migrations_dir = "prisma/migrations" 