-- Insert games
INSERT INTO Game (id, title, description, imageUrl, gameUrl, category, iframeWidth, iframeHeight, createdAt, updatedAt) VALUES
('1', 'Pac-Man', 'Classic maze chase game where you control Pac-Man to eat all dots while avoiding ghosts.', '/games/pacman.jpg', 'https://freepacman.org/', 'Arcade', 800, 600, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('2', 'Arkanoid', 'Classic brick-breaking game where you control a paddle to bounce the ball and break blocks.', '/games/arkanoid.jpg', 'https://arkanoid.online/', 'Arcade', 800, 600, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('3', 'Hextris', 'Rotate hexagonal blocks to match colors and clear lines in this unique puzzle game.', '/games/hextris.jpg', 'https://hextris.io/', 'Arcade', 800, 600, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('4', 'Duck Hunt', 'Classic shooting game where you aim to shoot ducks as they fly across the screen.', '/games/duckhunt.jpg', 'https://duckhuntjs.com/', 'Arcade', 800, 600, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('5', 'HexGL', 'Futuristic racing game with high-speed action on hexagonal tracks.', '/games/hexgl.jpg', 'https://hexgl.bkcore.com/play/', 'Action', 800, 600, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('6', 'Lost World', 'Explore a mysterious world filled with puzzles and challenges.', '/games/lostworld.jpg', 'https://lostworld.io/', 'Action', 800, 600, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('7', 'Powerline', 'Connect power nodes to create circuits in this challenging puzzle game.', '/games/powerline.jpg', 'https://powerline.io/', 'Action', 800, 600, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('8', 'Diep', 'Tank battle game where you upgrade your tank and fight other players.', '/games/diep.jpg', 'https://diep.io/', 'Action', 800, 600, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('9', 'Wings', 'Aerial combat game where you pilot aircraft in intense dogfights.', '/games/wings.jpg', 'https://wings.io/', 'Action', 800, 600, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('10', 'Starve', 'Survive in a harsh wilderness by gathering resources and crafting items.', '/games/starve.jpg', 'https://starve.io/', 'Action', 800, 600, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('11', 'Gartic', 'Draw and guess words in this multiplayer drawing game.', '/games/gartic.jpg', 'https://gartic.io/', 'Casual', 800, 600, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('12', 'Territorial', 'Capture territory and expand your influence in this strategy game.', '/games/territorial.jpg', 'https://territorial.io/', 'Strategy', 800, 600, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('13', 'Deeeep', 'Evolve and survive as different sea creatures in this underwater adventure.', '/games/deeeep.jpg', 'https://deeeep.io/', 'Action', 800, 600, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('14', 'Splix', 'Capture territory while avoiding other players lines.', '/games/splix.jpg', 'https://splix.io/', 'Strategy', 800, 600, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('15', 'Generals', 'Command armies and conquer territories in this strategic war game.', '/games/generals.jpg', 'https://generals.io/', 'Strategy', 800, 600, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('16', 'Slither', 'Grow your snake by eating glowing orbs while avoiding other players.', '/games/slither.jpg', 'https://slither.io/', 'Sports', 800, 600, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('17', 'Curve Fever', 'Draw lines to block other players while avoiding collisions.', '/games/curvefever.jpg', 'https://curvefever.pro', 'Sports', 800, 600, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('18', 'Evades', 'Dodge obstacles and enemies in this fast-paced survival game.', '/games/evades.jpg', 'https://evades.io/', 'Sports', 800, 600, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('19', 'Brutal', 'Fight waves of enemies in this intense action game.', '/games/brutal.jpg', 'https://brutal.io/', 'Sports', 800, 600, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('20', 'Wilds', 'Survive in a wilderness full of dangerous creatures and other players.', '/games/wilds.jpg', 'https://wilds.io/', 'Sports', 800, 600, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('21', 'Stabfish', 'Battle other sea creatures in this underwater fighting game.', '/games/stabfish.jpg', 'https://stabfish.io/', 'Sports', 800, 600, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('22', 'Krunker', 'Fast-paced first-person shooter with various game modes.', '/games/krunker.jpg', 'https://krunker.io/', 'Shooting', 800, 600, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('23', 'Shell Shock', 'Artillery game where you battle other tanks with various weapons.', '/games/shellshock.jpg', 'https://shellshock.io/', 'Shooting', 800, 600, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('24', 'Zombs Royale', 'Battle royale game with zombies and survival elements.', '/games/zombsroyale.jpg', 'https://zombsroyale.io/', 'Shooting', 800, 600, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('25', 'Surviv', '2D battle royale game with intense combat and strategy.', '/games/surviv.jpg', 'https://surviv.io/', 'Shooting', 800, 600, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('26', '1v1.LOL', 'Build and battle in this competitive building combat game.', '/games/1v1lol.jpg', 'https://1v1.lol/', 'Shooting', 800, 600, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP); 